services:
  api-gw:
    ports: !override
      - "127.0.0.1:8000:8000/tcp"

  supavisor:
    ports: !override
      - "127.0.0.1:5432:5432/tcp"
      - "127.0.0.1:6543:6543/tcp"

  auth:
    environment:
      GOTRUE_JWT_KEYS: '${JWT_KEYS:-[]}'

  realtime:
    environment:
      API_JWT_JWKS: '${JWT_JWKS:-{"keys":[]}}'

  storage:
    environment:
      JWT_JWKS: '${JWT_JWKS:-{"keys":[]}}'

  functions:
    environment:
      SUPABASE_JWKS: '${JWT_JWKS:-{"keys":[]}}'
