import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHmac, randomBytes } from "node:crypto";
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { bootstrapSecretGeneration, generationMutationLockPath, getCurrentSecretGeneration } from "./secret-generation.mjs";
import { activateEcSigningKeyRotation, ecSigningKeyRotationStatus, prepareEcSigningKeyRotation, readEcSigningKeyRotationPlan, rollbackEcSigningKeyRotation } from "./ec-signing-key-rotation-plan.mjs";
import { generateEphemeralEcSigningPair, signAsymmetricTranslationJwt } from "./ec-signing-key-rotation.mjs";

const NOW = 1_800_000_000;
function legacy(secret, role) { const header = Buffer.from(JSON.stringify({ alg: "HS256", typ: "JWT" })).toString("base64url"), payload = Buffer.from(JSON.stringify({ role, iss: "supabase", iat: NOW, exp: NOW + 300 })).toString("base64url"); return `${header}.${payload}.${createHmac("sha256", secret).update(`${header}.${payload}`).digest("base64url")}`; }
function gen4() { const pair = generateEphemeralEcSigningPair(), secret = randomBytes(32).toString("base64"), oct = { kty: "oct", k: Buffer.from(secret).toString("base64url"), alg: "HS256" }; return Buffer.from([["JWT_SECRET", secret], ["ANON_KEY", legacy(secret, "anon")], ["SERVICE_ROLE_KEY", legacy(secret, "service_role")], ["SUPABASE_PUBLISHABLE_KEY", "synthetic-public"], ["SUPABASE_SECRET_KEY", "synthetic-secret"], ["UNRELATED", "stable"], ["JWT_KEYS", JSON.stringify([pair.privateJwk, oct])], ["JWT_JWKS", JSON.stringify({ keys: [pair.publicJwk, oct] })], ["ANON_KEY_ASYMMETRIC", signAsymmetricTranslationJwt({ privateKey: pair.privateJwk, role: "anon", now: NOW })], ["SERVICE_ROLE_KEY_ASYMMETRIC", signAsymmetricTranslationJwt({ privateKey: pair.privateJwk, role: "service_role", now: NOW })]].map(([name, value]) => `${name}=${value}`).join("\n") + "\n"); }
async function fixture() { const tempRoot = await mkdtemp(join(tmpdir(), "godel-ec-plan-")), root = join(tempRoot, "repo"), protectedRoot = join(tempRoot, "protected"), supabaseEnvPath = join(tempRoot, "supabase.env"), godelEnvPath = join(tempRoot, "godel.env"); await mkdir(root); execFileSync("git", ["init"], { cwd: root }); execFileSync("git", ["config", "user.email", "test@example.invalid"], { cwd: root }); execFileSync("git", ["config", "user.name", "Test"], { cwd: root }); await writeFile(join(root, ".keep"), "fixture\n"); execFileSync("git", ["add", ".keep"], { cwd: root }); execFileSync("git", ["commit", "-m", "fixture"], { cwd: root }); await writeFile(supabaseEnvPath, gen4()); await writeFile(godelEnvPath, "GODEL=unchanged\n"); const value = { root, tempRoot, protectedRoot, supabaseEnvPath, godelEnvPath }; await bootstrapSecretGeneration({ ...value, apply: true }); return value; }
async function withFixture(run) { const value = await fixture(); try { await run(value); } finally { await rm(value.tempRoot, { recursive: true, force: true }); } }
async function prepare(value) { return prepareEcSigningKeyRotation({ ...value, apply: true }); }

test("prepare dry-run is side-effect free and apply publishes a structural immutable plan", async () => withFixture(async (value) => {
  const source = await getCurrentSecretGeneration(value), beforeSupabase = await readFile(value.supabaseEnvPath), beforeGodel = await readFile(value.godelEnvPath); const dry = await prepareEcSigningKeyRotation(value); assert.equal(dry.state, "DRY_RUN"); assert.equal((await getCurrentSecretGeneration(value)).generationId, source.generationId); assert.deepEqual(await readFile(value.supabaseEnvPath), beforeSupabase);
  const prepared = await prepare(value), plan = await readEcSigningKeyRotationPlan({ protectedRoot: value.protectedRoot, planId: prepared.planId }); assert.equal((await getCurrentSecretGeneration(value)).generationId, source.generationId); assert.deepEqual(await readFile(value.supabaseEnvPath), beforeSupabase); assert.deepEqual(await readFile(value.godelEnvPath), beforeGodel); assert.equal(plan.manifest.sourceGenerationId, source.generationId); assert.equal(plan.stages.GEN5.metadata.sourceGenerationId, source.generationId); assert.equal(plan.stages.GEN6.metadata.sourceGenerationId, prepared.stages.GEN5); assert.equal(plan.stages.GEN7.metadata.sourceGenerationId, prepared.stages.GEN6);
  const manifest = await readFile(join(value.protectedRoot, "external-secrets", "ec-rotation-plans", prepared.planId, "plan.json"), "utf8"); for (const forbidden of ["kid", "JWT", "JWK", "PRIVATE", "\"d\"\\s*:"]) assert.doesNotMatch(manifest, new RegExp(forbidden, "i"));
}));

test("only adjacent forward and rollback stages mutate the temporary live env", async () => withFixture(async (value) => {
  const prepared = await prepare(value), options = { ...value, planId: prepared.planId, apply: true }; await activateEcSigningKeyRotation({ ...options, toStage: "GEN5" }); assert.equal((await ecSigningKeyRotationStatus(options)).stage, "GEN5"); await activateEcSigningKeyRotation({ ...options, toStage: "GEN6" }); assert.equal((await ecSigningKeyRotationStatus(options)).stage, "GEN6"); await activateEcSigningKeyRotation({ ...options, toStage: "GEN7" }); assert.equal((await ecSigningKeyRotationStatus(options)).stage, "GEN7"); await rollbackEcSigningKeyRotation({ ...options, toStage: "GEN6" }); await rollbackEcSigningKeyRotation({ ...options, toStage: "GEN5" }); await rollbackEcSigningKeyRotation({ ...options, toStage: "GEN4" }); assert.equal((await ecSigningKeyRotationStatus(options)).stage, "GEN4");
}));

test("unsafe skips and an unrelated plan do not move the pointer", async () => withFixture(async (value) => {
  const first = await prepare(value), second = await prepare(value), source = await getCurrentSecretGeneration(value), options = { ...value, planId: first.planId }; await assert.rejects(() => activateEcSigningKeyRotation({ ...options, toStage: "GEN6" }), /UNSAFE_EC_ROTATION_STAGE_TRANSITION/); await assert.rejects(() => rollbackEcSigningKeyRotation({ ...options, toStage: "GEN4" }), /UNSAFE_EC_ROTATION_STAGE_TRANSITION/); assert.equal((await getCurrentSecretGeneration(value)).generationId, source.generationId); await activateEcSigningKeyRotation({ ...options, toStage: "GEN5", apply: true }); await assert.rejects(() => activateEcSigningKeyRotation({ ...value, planId: second.planId, toStage: "GEN6" }), /PLAN_NOT_CURRENTLY_ACTIVE/);
}));

test("rejects corrupt manifests and cleans unpublished preparation artifacts", async () => withFixture(async (value) => {
  await assert.rejects(() => prepareEcSigningKeyRotation({ ...value, apply: true, hooks: { beforePlanManifest: () => { throw new Error("INJECTED"); } } }), /INJECTED/); assert.equal((await readdir(join(value.protectedRoot, "external-secrets", "generations"))).length, 1); const prepared = await prepare(value), manifestPath = join(value.protectedRoot, "external-secrets", "ec-rotation-plans", prepared.planId, "plan.json"), manifest = JSON.parse(await readFile(manifestPath, "utf8")); manifest.unexpected = true; await writeFile(manifestPath, `${JSON.stringify(manifest)}\n`); await assert.rejects(() => readEcSigningKeyRotationPlan({ protectedRoot: value.protectedRoot, planId: prepared.planId }), /INVALID_EC_ROTATION_PLAN_MANIFEST/);
}));

test("rejects missing stages, bad generation chains, and corrupted protected snapshots", async () => withFixture(async (value) => {
  const prepared = await prepare(value), planRoot = join(value.protectedRoot, "external-secrets", "ec-rotation-plans", prepared.planId), manifestPath = join(planRoot, "plan.json"), originalManifest = await readFile(manifestPath, "utf8"), manifest = JSON.parse(originalManifest);
  for (const stage of ["GEN5", "GEN6", "GEN7"]) { const broken = structuredClone(manifest); delete broken.stages[stage]; await writeFile(manifestPath, `${JSON.stringify(broken)}\n`); await assert.rejects(() => readEcSigningKeyRotationPlan({ protectedRoot: value.protectedRoot, planId: prepared.planId }), /INVALID_EC_ROTATION_PLAN_MANIFEST/); }
  await writeFile(manifestPath, originalManifest); const metadataPath = join(value.protectedRoot, "external-secrets", "generations", prepared.stages.GEN6, "metadata.json"), originalMetadata = await readFile(metadataPath, "utf8"), metadata = JSON.parse(originalMetadata); metadata.reason = "legacy-jwt-rotation"; await writeFile(metadataPath, `${JSON.stringify(metadata)}\n`); await assert.rejects(() => readEcSigningKeyRotationPlan({ protectedRoot: value.protectedRoot, planId: prepared.planId }), /INVALID_EC_ROTATION_GENERATION_CHAIN/); await writeFile(metadataPath, originalMetadata);
  const godelPath = join(value.protectedRoot, "external-secrets", "generations", prepared.stages.GEN7, "godel.env"), originalGodel = await readFile(godelPath); await writeFile(godelPath, "GODEL=corrupted\n"); await assert.rejects(() => readEcSigningKeyRotationPlan({ protectedRoot: value.protectedRoot, planId: prepared.planId }), /EC_ROTATION_GODEL_SNAPSHOT_MISMATCH/); await writeFile(godelPath, originalGodel); await assert.rejects(() => readEcSigningKeyRotationPlan({ protectedRoot: value.protectedRoot, planId: "not-a-plan" }), /INVALID_EC_ROTATION_PLAN_ID/);
}));

test("binds every stage commit to the manifest and rejects source/stage aliases", async () => withFixture(async (value) => {
  const prepared = await prepare(value), manifestPath = join(value.protectedRoot, "external-secrets", "ec-rotation-plans", prepared.planId, "plan.json"), originalManifest = await readFile(manifestPath, "utf8"), metadataPath = join(value.protectedRoot, "external-secrets", "generations", prepared.stages.GEN5, "metadata.json"), originalMetadata = await readFile(metadataPath, "utf8"), metadata = JSON.parse(originalMetadata); metadata.repositoryCommit = "0".repeat(40); await writeFile(metadataPath, `${JSON.stringify(metadata)}\n`); await assert.rejects(() => readEcSigningKeyRotationPlan({ protectedRoot: value.protectedRoot, planId: prepared.planId }), /EC_ROTATION_PLAN_REPOSITORY_COMMIT_MISMATCH/); await writeFile(metadataPath, originalMetadata);
  const aliased = JSON.parse(originalManifest); aliased.stages.GEN5 = aliased.sourceGenerationId; await writeFile(manifestPath, `${JSON.stringify(aliased)}\n`); await assert.rejects(() => readEcSigningKeyRotationPlan({ protectedRoot: value.protectedRoot, planId: prepared.planId }), /INVALID_EC_ROTATION_PLAN_MANIFEST/);
}));

test("source and repository races fail before EC plan publication", async () => withFixture(async (value) => {
  const originalSupabase = await readFile(value.supabaseEnvPath); await assert.rejects(() => prepareEcSigningKeyRotation({ ...value, apply: true, hooks: { afterLockAcquired: async () => writeFile(value.supabaseEnvPath, `${originalSupabase}RACE=changed\n`) } }), /EXTERNAL_SECRET_GENERATION_MISMATCH/); assert.equal((await readdir(join(value.protectedRoot, "external-secrets", "generations"))).length, 1); await writeFile(value.supabaseEnvPath, originalSupabase); assert.equal((await getCurrentSecretGeneration(value)).match, true);
  const dirty = join(value.root, "race"); try { await assert.rejects(() => prepareEcSigningKeyRotation({ ...value, apply: true, hooks: { afterLockAcquired: () => writeFile(dirty, "dirty\n") } }), /REPOSITORY_MUST_BE_CLEAN/); assert.equal((await readdir(join(value.protectedRoot, "external-secrets", "generations"))).length, 1); } finally { await rm(dirty, { force: true }); }
}));

test("cleanup failure preserves the lock and never creates an actionable manifest", async () => withFixture(async (value) => {
  await assert.rejects(() => prepareEcSigningKeyRotation({ ...value, apply: true, hooks: { beforePlanManifest: () => { throw new Error("INJECTED"); }, removePublishedGeneration: () => { throw new Error("REMOVE_FAILED"); } } }), /EC_ROTATION_PLAN_CLEANUP_FAILED/); assert.ok(await readFile(generationMutationLockPath(value.protectedRoot))); assert.equal((await getCurrentSecretGeneration(value)).match, true); await assert.rejects(() => readdir(join(value.protectedRoot, "external-secrets", "ec-rotation-plans")), /ENOENT/);
}));

test("pre-pointer failures compensate and post-pointer failures preserve the lock", async () => withFixture(async (value) => {
  const prepared = await prepare(value), source = await getCurrentSecretGeneration(value), options = { ...value, planId: prepared.planId, toStage: "GEN5", apply: true }; await assert.rejects(() => activateEcSigningKeyRotation({ ...options, hooks: { afterEnvUpdate: () => { throw new Error("INJECTED"); } } }), /INJECTED/); assert.equal((await getCurrentSecretGeneration(value)).generationId, source.generationId); await assert.rejects(() => activateEcSigningKeyRotation({ ...options, hooks: { afterPointerCommit: () => { throw new Error("INJECTED"); } } }), /EC_SIGNING_ROTATION_COMMITTED_UNVERIFIED/); assert.ok(await readFile(generationMutationLockPath(value.protectedRoot)));
}));
